    /*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

/**
 *
 * @author lucas
 */

import Sistema.Departamento;
import Sistema.Funcionario;
import Sistema.Tecnico;
import Sistema.Efetivo;
import Sistema.Substituto;
import Controlador.Controlador;
import javax.swing.JOptionPane;


public class Interface extends javax.swing.JFrame {
    
    private Controlador controlador;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Interface.class.getName());

    /**
     * Creates new form Interface
     */
    public Interface() {
        initComponents();
        controlador = new Controlador("Universidade X");

        // Preencher os comboBoxes corretamente
        jComboTipo.removeAllItems();
        jComboTipo.addItem("Tecnico");
        jComboTipo.addItem("Efetivo");
        jComboTipo.addItem("Substituto");

        jComboNivel.removeAllItems();
        jComboNivel.addItem("A");
        jComboNivel.addItem("B");
        jComboNivel.addItem("C");
        
             jComboTipo.addActionListener(evt -> {
    String tipo = (String) jComboTipo.getSelectedItem();

    jLabelArea.setVisible(false);
    jTextFieldArea.setVisible(false);
    jLabelCarga.setVisible(false);
    jTextFieldCarga.setVisible(false);
    jLabelFuncao.setVisible(false);
    jTextFieldFuncao.setVisible(false);
    jLabelTitulo.setVisible(false);
    jTextFieldTitulo.setVisible(false);

    switch (tipo) {
        case "Efetivo" -> {
            jLabelArea.setVisible(true);
            jTextFieldArea.setVisible(true);
            jLabelTitulo.setVisible(true);
            jTextFieldTitulo.setVisible(true);
        }
        case "Substituto" -> {
            jLabelCarga.setVisible(true);
            jTextFieldCarga.setVisible(true);
            jLabelTitulo.setVisible(true);
            jTextFieldTitulo.setVisible(true);
        }
        case "Tecnico" -> {
            jLabelFuncao.setVisible(true);
            jTextFieldFuncao.setVisible(true);
        }
    }

        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNomeDepartamento = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtCodigoDepartamento = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jComboTipo = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        cmbDepartamento1 = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldCodigo = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldNome = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldSalario = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jComboNivel = new javax.swing.JComboBox<>();
        btnCadastrarFuncionari = new javax.swing.JButton();
        jLabelCarga = new javax.swing.JLabel();
        jLabelArea = new javax.swing.JLabel();
        jTextFieldArea = new javax.swing.JTextField();
        jTextFieldCarga = new javax.swing.JTextField();
        jLabelFuncao = new javax.swing.JLabel();
        jTextFieldFuncao = new javax.swing.JTextField();
        jLabelTitulo = new javax.swing.JLabel();
        jTextFieldTitulo = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        BtnRelatorio_fun = new javax.swing.JButton();
        exibirTecnicos = new javax.swing.JButton();
        Geral = new javax.swing.JButton();
        exibirInformaçõesDepartamento = new javax.swing.JButton();
        exibirDocentes = new javax.swing.JButton();
        exibirFuncionarioNome = new javax.swing.JButton();
        exibirDoscentesSubstitutos = new javax.swing.JButton();
        exibirDocentesEfetivos = new javax.swing.JButton();
        exibirFuncionarioCodigo = new javax.swing.JButton();
        codigoDepartamentoBuscar = new javax.swing.JTextField();
        textoCodigoFuncionario = new javax.swing.JTextField();
        textoNomeFuncionario1 = new javax.swing.JTextField();
        btnBuscarFaixaSalario = new javax.swing.JButton();
        jTextFieldSalMin = new javax.swing.JTextField();
        jTextFieldSalMax = new javax.swing.JTextField();
        btnBuscarDepartamentosPorGasto = new javax.swing.JButton();
        jTextFieldGastoMin = new javax.swing.JTextField();
        jTextFieldGastoMax = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Cadastrar Departamento");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Código do Departamento:");

        txtNomeDepartamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeDepartamentoActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Nome do Departamento:");

        txtCodigoDepartamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoDepartamentoActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(204, 204, 204));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setText("Adicionar Departamento");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(312, Short.MAX_VALUE)
                        .addComponent(txtNomeDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton1)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(87, 87, 87)
                        .addComponent(txtCodigoDepartamento)))
                .addGap(35, 35, 35))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(39, 39, 39)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(581, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(txtNomeDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtCodigoDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addComponent(jButton1)
                .addContainerGap(102, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(72, 72, 72)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(232, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Departamentos", jPanel1);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Cadastrar Funcionário");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Departamento:");

        jComboTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Código:");

        cmbDepartamento1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbDepartamento1ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Tipo de Funcionário:");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Nome:");

        jTextFieldNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNomeActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("Salário Base:");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("Nível:");

        jComboNivel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnCadastrarFuncionari.setBackground(new java.awt.Color(204, 204, 204));
        btnCadastrarFuncionari.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCadastrarFuncionari.setText("Adicionar Funcionario");
        btnCadastrarFuncionari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarFuncionariActionPerformed(evt);
            }
        });

        jLabelCarga.setText("Carga Horária:");

        jLabelArea.setText("Área:");

        jTextFieldArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldAreaActionPerformed(evt);
            }
        });

        jTextFieldCarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCargaActionPerformed(evt);
            }
        });

        jLabelFuncao.setText("Função:");

        jTextFieldFuncao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldFuncaoActionPerformed(evt);
            }
        });

        jLabelTitulo.setText("Titulação:");

        jTextFieldTitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTituloActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldNome))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(145, 145, 145))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(cmbDepartamento1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(jLabelFuncao, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldFuncao, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(58, 58, 58)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabelCarga)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jTextFieldArea, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(jTextFieldCarga, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jTextFieldTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldSalario, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jComboNivel, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(59, 59, 59)
                                .addComponent(btnCadastrarFuncionari)))))
                .addContainerGap(104, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addContainerGap(437, Short.MAX_VALUE)
                    .addComponent(jLabelArea, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(308, 308, 308)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbDepartamento1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelTitulo)
                            .addComponent(jTextFieldTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelCarga)
                            .addComponent(jTextFieldCarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelFuncao)
                            .addComponent(jTextFieldFuncao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldSalario, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboNivel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCadastrarFuncionari))
                .addContainerGap(19, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(44, 44, 44)
                    .addComponent(jLabelArea)
                    .addContainerGap(284, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Funcionários", jPanel2);

        BtnRelatorio_fun.setText("Relatório Funcinário");
        BtnRelatorio_fun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRelatorio_funActionPerformed(evt);
            }
        });

        exibirTecnicos.setText("Exibir técnico");
        exibirTecnicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exibirTecnicosActionPerformed(evt);
            }
        });

        Geral.setText("Geral");
        Geral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GeralActionPerformed(evt);
            }
        });

        exibirInformaçõesDepartamento.setText("Exibir informações de um departamento");
        exibirInformaçõesDepartamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exibirInformaçõesDepartamentoActionPerformed(evt);
            }
        });

        exibirDocentes.setText("Exibir docentes");
        exibirDocentes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exibirDocentesActionPerformed(evt);
            }
        });

        exibirFuncionarioNome.setText("Exibir Funcionário por nome");
        exibirFuncionarioNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exibirFuncionarioNomeActionPerformed(evt);
            }
        });

        exibirDoscentesSubstitutos.setText("Exibir Doscentes substitutos");
        exibirDoscentesSubstitutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exibirDoscentesSubstitutosActionPerformed(evt);
            }
        });

        exibirDocentesEfetivos.setText("Exibir doscentes efetivos");
        exibirDocentesEfetivos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exibirDocentesEfetivosActionPerformed(evt);
            }
        });

        exibirFuncionarioCodigo.setText("Exibir Funcionário por código");
        exibirFuncionarioCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exibirFuncionarioCodigoActionPerformed(evt);
            }
        });

        codigoDepartamentoBuscar.setText("Código do departamento");
        codigoDepartamentoBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codigoDepartamentoBuscarActionPerformed(evt);
            }
        });

        textoCodigoFuncionario.setText("Código do funcionário");

        textoNomeFuncionario1.setText("Nome do funcionário");

        btnBuscarFaixaSalario.setText("Buscar funcionario por salário");
        btnBuscarFaixaSalario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarFaixaSalarioActionPerformed(evt);
            }
        });

        jTextFieldSalMin.setText("min");
        jTextFieldSalMin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSalMinActionPerformed(evt);
            }
        });

        jTextFieldSalMax.setText("max");

        btnBuscarDepartamentosPorGasto.setText("Buscar departamento por gasto");
        btnBuscarDepartamentosPorGasto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarDepartamentosPorGastoActionPerformed(evt);
            }
        });

        jTextFieldGastoMin.setText("min");
        jTextFieldGastoMin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldGastoMinActionPerformed(evt);
            }
        });

        jTextFieldGastoMax.setText("max");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(exibirTecnicos)
                    .addComponent(exibirDocentes)
                    .addComponent(exibirDoscentesSubstitutos)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(exibirFuncionarioNome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textoNomeFuncionario1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(exibirDocentesEfetivos)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(exibirInformaçõesDepartamento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(codigoDepartamentoBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(exibirFuncionarioCodigo)
                        .addGap(2, 2, 2)
                        .addComponent(textoCodigoFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(BtnRelatorio_fun)
                        .addGap(86, 86, 86)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(btnBuscarDepartamentosPorGasto)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldGastoMin, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldGastoMax, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(btnBuscarFaixaSalario)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldSalMin, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldSalMax, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(227, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(10, 10, 10)
                    .addComponent(Geral)
                    .addContainerGap(725, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnRelatorio_fun)
                    .addComponent(btnBuscarFaixaSalario)
                    .addComponent(jTextFieldSalMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldSalMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBuscarDepartamentosPorGasto)
                    .addComponent(jTextFieldGastoMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldGastoMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(exibirTecnicos)
                .addGap(9, 9, 9)
                .addComponent(exibirDocentes)
                .addGap(18, 18, 18)
                .addComponent(exibirDocentesEfetivos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(exibirDoscentesSubstitutos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(exibirInformaçõesDepartamento)
                    .addComponent(codigoDepartamentoBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(exibirFuncionarioCodigo)
                    .addComponent(textoCodigoFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(exibirFuncionarioNome)
                    .addComponent(textoNomeFuncionario1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(66, 66, 66)
                    .addComponent(Geral)
                    .addContainerGap(256, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Relatórios", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 807, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(250, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTituloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTituloActionPerformed

    private void jTextFieldFuncaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldFuncaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldFuncaoActionPerformed

    private void jTextFieldCargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCargaActionPerformed

    private void jTextFieldAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldAreaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldAreaActionPerformed

    private void btnCadastrarFuncionariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarFuncionariActionPerformed
        String nome = jTextFieldNome.getText();
        String codigoFuncionario = jTextFieldCodigo.getText();
        String salarioStr = jTextFieldSalario.getText();
        String tipo = (String) jComboTipo.getSelectedItem();
        String nivel = (String) jComboNivel.getSelectedItem();
        String codigoDepartamento = (String) cmbDepartamento1.getSelectedItem();
        String area = jTextFieldArea.getText();
        String titulo = jTextFieldTitulo.getText();
        String cargaStr = jTextFieldCarga.getText();

        if (nome.isEmpty() || codigoFuncionario.isEmpty() || salarioStr.isEmpty() || codigoDepartamento == null) {
            JOptionPane.showMessageDialog(this, "Preencha todos os campos corretamente.");
            return;
        }

        double salario;
        try {
            salario = Double.parseDouble(salarioStr);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Salário inválido.");
            return;
        }

        Funcionario f = null;
        switch (tipo) {
            case "Tecnico" -> {
                String funcao = jTextFieldFuncao.getText();
                if (funcao.isEmpty()) {
                    JOptionPane.showMessageDialog(this, "Informe a função do Técnico.");
                    return;
                }
                f = new Tecnico(salario, nome, codigoFuncionario, nivel, funcao);
            }
            case "Efetivo" -> {
                if (area.isEmpty()) {
                    JOptionPane.showMessageDialog(this, "Informe a área do Efetivo.");
                    return;
                }
                f = new Efetivo(salario, nome, codigoFuncionario, 0, titulo, nivel, area);
            }
            case "Substituto" -> {
                int cargaHoraria;
                try {
                    cargaHoraria = Integer.parseInt(cargaStr);
                } catch (NumberFormatException e) {
                    JOptionPane.showMessageDialog(this, "Carga horária inválida.");
                    return;
                }
                f = new Substituto(salario, nome, codigoFuncionario, titulo, nivel, cargaHoraria);
            }
        }

        if (f != null) {
            controlador.adicionarFuncionario(codigoDepartamento, f);
            JOptionPane.showMessageDialog(this, "Funcionário cadastrado com sucesso!");
            jTextFieldNome.setText("");
            jTextFieldCodigo.setText("");
            jTextFieldSalario.setText("");
            jTextFieldArea.setText("");
            jTextFieldCarga.setText("");
            jTextFieldTitulo.setText("");
        } else {
            JOptionPane.showMessageDialog(this, "Erro ao criar funcionário.");
        }
    }//GEN-LAST:event_btnCadastrarFuncionariActionPerformed

    private void jTextFieldNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNomeActionPerformed

    private void cmbDepartamento1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbDepartamento1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbDepartamento1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String nomeDepartamento = txtNomeDepartamento.getText();
        String codigoDepartamento = txtCodigoDepartamento.getText();

        if (nomeDepartamento.isEmpty() || codigoDepartamento.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Preencha todos os campos!", "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }

        Departamento novoDepartamento = new Departamento(codigoDepartamento, nomeDepartamento);
        controlador.adicionarDepartamento(novoDepartamento);

        JOptionPane.showMessageDialog(this, "Departamento '" + nomeDepartamento + "' (Código: " + codigoDepartamento + ") adicionado com sucesso!", "Cadastro Realizado", JOptionPane.INFORMATION_MESSAGE);

        txtNomeDepartamento.setText("");
        txtCodigoDepartamento.setText("");
        cmbDepartamento1.addItem(codigoDepartamento);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtCodigoDepartamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoDepartamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoDepartamentoActionPerformed

    private void txtNomeDepartamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeDepartamentoActionPerformed

    }//GEN-LAST:event_txtNomeDepartamentoActionPerformed

    private void BtnRelatorio_funActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRelatorio_funActionPerformed
      String resultado = controlador.exibirTodosFuncionarios();
    if (resultado.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Nenhum funcionário cadastrado.");
    } else {
        JOptionPane.showMessageDialog(this, resultado, "Todos os Funcionários", JOptionPane.INFORMATION_MESSAGE);
    }
    }//GEN-LAST:event_BtnRelatorio_funActionPerformed

    private void exibirTecnicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exibirTecnicosActionPerformed
    String relatorioTecnicos = controlador.exibirTecnicos();
    exibirResultadoRelatorio("Técnicos", relatorioTecnicos);
    }//GEN-LAST:event_exibirTecnicosActionPerformed
private void exibirResultadoRelatorio(String titulo, String conteudo) {
    if (conteudo == null || conteudo.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Nenhum(a) " + titulo + " encontrado(a).");
    } else {
        JOptionPane.showMessageDialog(this, conteudo, "Relatório: " + titulo, JOptionPane.INFORMATION_MESSAGE);
    }
}

    private void GeralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GeralActionPerformed
          String funcionarios = controlador.exibirTodosFuncionarios();
    String[] departamentos = controlador.resumoDepartamentos();

    if ((funcionarios == null || funcionarios.isEmpty()) && (departamentos == null || departamentos.length == 0)) {
        JOptionPane.showMessageDialog(this, "Nenhum dado encontrado.");
        return;
    }

    StringBuilder sb = new StringBuilder();
    sb.append("=== Funcionários ===\n").append(funcionarios).append("\n");
    sb.append("=== Departamentos ===\n");
    for (String d : departamentos) {
        sb.append(d).append("\n");
    }

    JOptionPane.showMessageDialog(this, sb.toString(), "Relatório Geral", JOptionPane.INFORMATION_MESSAGE);

    }//GEN-LAST:event_GeralActionPerformed

    private void exibirInformaçõesDepartamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exibirInformaçõesDepartamentoActionPerformed
           String codigo = codigoDepartamentoBuscar.getText().trim();
    if (codigo.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Informe o código do departamento.");
        return;
    }
    String resultado = controlador.relatorioPorDepartamento(codigo);
    if (resultado == null || resultado.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Departamento não encontrado ou sem funcionários.");
    } else {
        JOptionPane.showMessageDialog(this, resultado, "Relatório do Departamento", JOptionPane.INFORMATION_MESSAGE);
    }
    }//GEN-LAST:event_exibirInformaçõesDepartamentoActionPerformed

    private void exibirDocentesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exibirDocentesActionPerformed
            String relatorioDocentes = controlador.exibirDocentes();
    exibirResultadoRelatorio("Docentes", relatorioDocentes);
    }//GEN-LAST:event_exibirDocentesActionPerformed

    private void exibirFuncionarioNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exibirFuncionarioNomeActionPerformed
           String nome = textoNomeFuncionario1.getText().trim();
    if (nome.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Informe o nome do funcionário.");
        return;
    }
    String resultado = controlador.buscarFuncionarioPorNomeReturn(nome);
    if (resultado == null || resultado.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Funcionário não encontrado.");
    } else {
        JOptionPane.showMessageDialog(this, resultado, "Funcionário Encontrado", JOptionPane.INFORMATION_MESSAGE);
    }
    }//GEN-LAST:event_exibirFuncionarioNomeActionPerformed

    private void exibirDoscentesSubstitutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exibirDoscentesSubstitutosActionPerformed
           String relatorioSubstitutos = controlador.exibirSubstitutos();
    exibirResultadoRelatorio("Docentes Substitutos", relatorioSubstitutos);
    }//GEN-LAST:event_exibirDoscentesSubstitutosActionPerformed

    private void exibirDocentesEfetivosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exibirDocentesEfetivosActionPerformed
      String relatorioEfetivos = controlador.exibirEfetivos();
    exibirResultadoRelatorio("Docentes Efetivos", relatorioEfetivos);
    }//GEN-LAST:event_exibirDocentesEfetivosActionPerformed

    private void exibirFuncionarioCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exibirFuncionarioCodigoActionPerformed
      String codigo = textoCodigoFuncionario.getText().trim();
    if (codigo.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Informe o código do funcionário.");
        return;
    }
    String resultado = controlador.buscarFuncionarioPorCodigoReturn(codigo);
    if (resultado == null || resultado.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Funcionário não encontrado.");
    } else {
        JOptionPane.showMessageDialog(this, resultado, "Funcionário Encontrado", JOptionPane.INFORMATION_MESSAGE);
    }
    }//GEN-LAST:event_exibirFuncionarioCodigoActionPerformed

    private void codigoDepartamentoBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codigoDepartamentoBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codigoDepartamentoBuscarActionPerformed

    private void jTextFieldSalMinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSalMinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldSalMinActionPerformed

    private void btnBuscarFaixaSalarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarFaixaSalarioActionPerformed
            try {
        double min = Double.parseDouble(jTextFieldSalMin.getText());
        double max = Double.parseDouble(jTextFieldSalMax.getText());
        String resultado = controlador.funcionariosPorFaixaSalarialReturn(min, max);
        exibirResultadoRelatorio("Funcionários na Faixa Salarial", resultado);
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Informe valores válidos para salário mínimo e máximo.");
    }
    }//GEN-LAST:event_btnBuscarFaixaSalarioActionPerformed

    private void btnBuscarDepartamentosPorGastoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarDepartamentosPorGastoActionPerformed
           try {
        double min = Double.parseDouble(jTextFieldGastoMin.getText());
        double max = Double.parseDouble(jTextFieldGastoMax.getText());
        String[] resultado = controlador.resumoPorFaixaDeGastoReturn(min, max);
        if (resultado.length == 0) {
            JOptionPane.showMessageDialog(this, "Nenhum departamento com gasto nessa faixa.");
        } else {
            StringBuilder sb = new StringBuilder();
            for (String s : resultado) sb.append(s).append("\n");
            JOptionPane.showMessageDialog(this, sb.toString(), "Departamentos na Faixa de Gasto", JOptionPane.INFORMATION_MESSAGE);
        }
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Informe valores válidos para gasto mínimo e máximo.");
    }
    }//GEN-LAST:event_btnBuscarDepartamentosPorGastoActionPerformed

    private void jTextFieldGastoMinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldGastoMinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldGastoMinActionPerformed


    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Interface().setVisible(true));
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnRelatorio_fun;
    private javax.swing.JButton Geral;
    private javax.swing.JButton btnBuscarDepartamentosPorGasto;
    private javax.swing.JButton btnBuscarFaixaSalario;
    private javax.swing.JButton btnCadastrarFuncionari;
    private javax.swing.JComboBox<String> cmbDepartamento1;
    private javax.swing.JTextField codigoDepartamentoBuscar;
    private javax.swing.JButton exibirDocentes;
    private javax.swing.JButton exibirDocentesEfetivos;
    private javax.swing.JButton exibirDoscentesSubstitutos;
    private javax.swing.JButton exibirFuncionarioCodigo;
    private javax.swing.JButton exibirFuncionarioNome;
    private javax.swing.JButton exibirInformaçõesDepartamento;
    private javax.swing.JButton exibirTecnicos;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboNivel;
    private javax.swing.JComboBox<String> jComboTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelArea;
    private javax.swing.JLabel jLabelCarga;
    private javax.swing.JLabel jLabelFuncao;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextFieldArea;
    private javax.swing.JTextField jTextFieldCarga;
    private javax.swing.JTextField jTextFieldCodigo;
    private javax.swing.JTextField jTextFieldFuncao;
    private javax.swing.JTextField jTextFieldGastoMax;
    private javax.swing.JTextField jTextFieldGastoMin;
    private javax.swing.JTextField jTextFieldNome;
    private javax.swing.JTextField jTextFieldSalMax;
    private javax.swing.JTextField jTextFieldSalMin;
    private javax.swing.JTextField jTextFieldSalario;
    private javax.swing.JTextField jTextFieldTitulo;
    private javax.swing.JTextField textoCodigoFuncionario;
    private javax.swing.JTextField textoNomeFuncionario1;
    private javax.swing.JTextField txtCodigoDepartamento;
    private javax.swing.JTextField txtNomeDepartamento;
    // End of variables declaration//GEN-END:variables
}
